add-recommendations
Artemev1986/java-filmorate pull request #8
Opened 2022-07-20 21:56 UTC by PavlovILYA

2022-07-20 22:02 UTC, PavlovILYA commented
На данный момент падают __29 тестов__
__Все они связаны с режиссерами__

Отчет:
[add-recommendations.postman_test_run.txt](https://github.com/Artemev1986/java-filmorate/files/9154736/add-recommendations.postman_test_run.txt)

2022-07-21 05:55 UTC, Artemev1986 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        this.filmService = filmService;
Инжектить один сервис в другой очень плохо. Мне за предыдущий ревьюер по ушам надавал)
Народ объяснил это следующим образом. Нарушается 'идеология'. сервис для пользователей должен заниматься бизнес логикой только для пользователей и не должен ничего знать о каком либо другом сервисе и тем более иметь возможность пользоваться его методами.

2022-07-21 06:25 UTC, Artemev1986 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        log.info("Recommendations for user {}: {}", id, recommendations);
Я подобные сообщения в debug выделяю, т.к. они помогают понять при отладке, что выполнился запрос или нет. Но я точно не уверен как правильно

2022-07-21 06:42 UTC, Artemev1986 requested changes
Всё отлично, но в одном месте надо подправить. См. коммент по инжекции

2022-07-21 07:13 UTC, Artemev1986 commented
Ещё у тебя нет тестов. Не знаю точно нужны ли они, но может имеет смысл сделать одни для галочки?)

2022-07-21 08:48 UTC, PavlovILYA commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        this.filmService = filmService;
Изначально инжектил filmStorage! 
Но:
1) Метод getById возвращает Optional<Film>, из-за чего нельзя стримы грамотно использовать при выдаче рекомендаций
2) Но это пол-беды. Если использовать filmStorage.getFilmById, то жанры не заполнятся! Из-за этого не проходят тесты!

P.S. В своей реализации я заполняю жанры внутри FilmStorage, выдавая готовый объект. В твоей реализации окончательно готовый объект выдает только FilmService. Поэтому я тут заинжектил именно сервис, а не дао

2022-07-23 04:16 UTC, PavlovILYA commented
Теперь в UserService используется FilmStorage, а не FilmService

2022-07-23 08:29 UTC, Artemev1986 approved these changes

2022-07-25 09:20 UTC, merged